### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
lista = []
for i in range(20):
    lista.append(i)
    
print(lista)

lista2 = [i for i in range(20)]
print(lista2)


lista = []
parola = "Python"
for i in parola:
    lista.append(i)
    
print(lista)

lista2 = [i for i in parola]

print(lista2)


lista = []
for i in range(10):
    lista.append(i*i)
    
print(lista)

lista2 = [i*i for i in range(10)]

print(lista2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
['P', 'y', 't', 'h', 'o', 'n']
['P', 'y', 't', 'h', 'o', 'n']
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [60]:
import numpy as np

num_primi = np.array([1,2,3,5,7])
print(num_primi)
print(len(num_primi))
print(num_primi.size)

#tipo di dato = INT

print(num_primi.dtype)
#e davvero int --> int32

def primo():
    lista = []
    for i in range(1,10):
        isprimo = 1
        for j in range(2,i):
            if i % j == 0:
                isprimo = 0
        if(isprimo == 1):
            lista += [i]
        else:
            i += 1
    return lista

num_primi2 = np.array(primo())
print(num_primi2)

    

[1 2 3 5 7]
5
5
int32
[1 2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [ ]:
import random as rd

a = np.array(np.arange(10,21))
print(a)

b = a[3:8]
print(b)

c = a[::-1]
print(c)

res = a / c
print(res)

##Divisione per due liste
lista = [i for i in range(10)]
lista
lista2 = [2 for i in range(10)]
lista2

res2 = []
for i in range(10):
    res2.append(lista[i] / lista2[i])
    
print(res2)

[10 11 12 13 14 15 16 17 18 19 20]
[13 14 15 16 17]
[20 19 18 17 16 15 14 13 12 11 10]
[0.5        0.57894737 0.66666667 0.76470588 0.875      1.
 1.14285714 1.30769231 1.5        1.72727273 2.        ]
[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]
