### **Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [16]:
import numpy as np
import random

a = [random.uniform(0,1) for i in range(30)]

a = np.array(a).reshape(10,3)

b = a[np.arange(10), np.abs(a-0.5).argmin(1)]

print(a)
print(b)

[[0.0134803  0.50593271 0.71922142]
 [0.70397452 0.31714684 0.7911645 ]
 [0.26872304 0.30075494 0.95210374]
 [0.70238649 0.53748326 0.95210485]
 [0.70602964 0.01444956 0.59124187]
 [0.6759818  0.03422034 0.10203267]
 [0.96677911 0.17939086 0.36523665]
 [0.96125736 0.9601844  0.33529284]
 [0.79597902 0.72878731 0.64399388]
 [0.68331324 0.38260878 0.42593161]]
[0.50593271 0.31714684 0.30075494 0.53748326 0.59124187 0.6759818
 0.36523665 0.33529284 0.64399388 0.42593161]
