### **Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [14]:
import numpy as np
import random

a = [random.uniform(0,1) for i in range(30)]

a = np.array(a).reshape(10,3)

b = a[np.arange(10), np.abs(a-0.5).argmin(1)]

print(a)
print(b)

#usando il fancy indexing
a =np.random.rand(10,3)

colonne = np.abs(a -0.5).argmin(axis=1)

righe = np.arange(a.shape[0])

b = a[righe, colonne]

print("\n\n\nIn classe: \n",a)
print(b)

[[0.33561446 0.49829354 0.20831827]
 [0.31206534 0.43104899 0.13680627]
 [0.57975639 0.11398556 0.44411943]
 [0.36773896 0.06380888 0.55111673]
 [0.79549773 0.22491465 0.10964327]
 [0.44054633 0.32495877 0.82556155]
 [0.27810368 0.77575507 0.69662256]
 [0.3985901  0.76687207 0.66828937]
 [0.81490734 0.51709592 0.78122914]
 [0.14490186 0.18204914 0.00727716]]
[0.49829354 0.43104899 0.44411943 0.55111673 0.22491465 0.44054633
 0.69662256 0.3985901  0.51709592 0.18204914]



In classe: 
 [[0.42058016 0.92603173 0.86584158]
 [0.68958091 0.09951364 0.57238506]
 [0.32767346 0.02931664 0.76705977]
 [0.68764476 0.17596005 0.76370601]
 [0.1598191  0.5633662  0.59747708]
 [0.77750824 0.09651981 0.84858183]
 [0.71221786 0.73226843 0.25696993]
 [0.62647307 0.5133169  0.28840663]
 [0.8449619  0.93830783 0.53609643]
 [0.71717144 0.73929529 0.89687981]]
[0.42058016 0.57238506 0.32767346 0.68764476 0.5633662  0.77750824
 0.71221786 0.5133169  0.53609643 0.71717144]
