# **Operazioni su Array**
Crea un array `a` 2D senza digitarlo esplicitamente e genera due nuovi array `b` contenente la sua seconda e quarta riga e `c` contenente solo la terza colonna. Dividi ogni colonna dell'array `a` elemento per elemento con l'array `c`.

In [3]:
import numpy as np

# Creazione dell'array 2D
a = np.arange(1, 32, 2).reshape(4, 4)

aa = np.array([np.array([i for i in range (1,11)]) * j for j in range (1,11)])

b = a[[1, 3], :]

c = a[:, 2]

risultato = a / c

# Stampa dei risultati
print("Array a:\n", a)
print("\nAlternativa aa:\n", aa)
print("\nArray b (2ª e 4ª riga di a):\n", b)
print("\nArray c (3ª colonna di a):\n", c)
print("\nRisultato della divisione:\n", risultato)

Array a:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]

Alternativa aa:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

Array b (2ª e 4ª riga di a):
 [[ 9 11 13 15]
 [25 27 29 31]]

Array c (3ª colonna di a):
 [ 5 13 21 29]

Risultato della divisione:
 [[0.2        0.23076923 0.23809524 0.24137931]
 [1.8        0.84615385 0.61904762 0.51724138]
 [3.4        1.46153846 1.         0.79310345]
 [5.         2.07692308 1.38095238 1.06896552]]
