# **Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [24]:
import numpy as np

# Creazione dell'array 1D
a = np.arange(1, 20)

b = a[5:15]

c = a[::-1]

res1 = a / c

l1 = [1,2,3,4,5,6,7,8,9]

l2 = [9,8,7,6,5,4,3,2,1]

res2 = [l1[i] / l2[i] for i in range(len(l1))]

print("Array a:\n", a)
print("\nArray b sottostringa:\n", b)
print("\nArray c reverse:\n", c)
print("\nRisultato della divisione:\n", res1)
print("\n Risultato divisione liste:\n", res2)


Array a:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array b sottostringa:
 [ 6  7  8  9 10 11 12 13 14 15]

Array c reverse:
 [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]

Risultato della divisione:
 [ 0.05263158  0.11111111  0.17647059  0.25        0.33333333  0.42857143
  0.53846154  0.66666667  0.81818182  1.          1.22222222  1.5
  1.85714286  2.33333333  3.          4.          5.66666667  9.
 19.        ]

 Risultato divisione liste:
 [0.1111111111111111, 0.25, 0.42857142857142855, 0.6666666666666666, 1.0, 1.5, 2.3333333333333335, 4.0, 9.0]
