# **Operazioni su Array**
Crea un array `a` 2D senza digitarlo esplicitamente e genera due nuovi array `b` contenente la sua seconda e quarta riga e `c` contenente solo la terza colonna. Dividi ogni colonna dell'array `a` elemento per elemento con l'array `c`.

In [ ]:
import numpy as np

# Creazione dell'array 2D
a = np.arange(1, 32, 2).reshape(4, 4)

b = a[[1, 3], :]

c = a[:, 2]

risultato = a / c

# Stampa dei risultati
print("Array a:\n", a)
print("\nArray b (2ª e 4ª riga di a):\n", b)
print("\nArray c (3ª colonna di a):\n", c)
print("\nRisultato della divisione:\n", risultato)

Array a:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]

Array b (2ª e 4ª riga di a):
 [[ 9 11 13 15]
 [25 27 29 31]]

Array c (3ª colonna di a):
 [ 5 13 21 29]

Risultato della divisione:
 [[0.2        0.23076923 0.23809524 0.24137931]
 [1.8        0.84615385 0.61904762 0.51724138]
 [3.4        1.46153846 1.         0.79310345]
 [5.         2.07692308 1.38095238 1.06896552]]
